/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "android/log.h"


//    JNIEXPORT jint JNICALL Java_com_cundong_utils_PatchUtils_patch
//    (JNIEnv *, jclass, jstring, jstring, jstring);
int applypatch(int argc, char * argv[]);
#define LOG_TAG "test"

#define ALOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define ALOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define ALOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG,__VA_ARGS__)
#define ALOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#define ALOGF(...)  __android_log_print(ANDROID_LOG_FATAL,LOG_TAG,__VA_ARGS__)

