/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cundong_utils_JDiff */

#ifndef _Included_com_cundong_utils_JDiff
#define _Included_com_cundong_utils_JDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cundong_utils_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
int genpatch(int argc, char *argv[]);

#ifdef __cplusplus
}
#endif
#endif
